name: Web Activation

on: workflow_dispatch

jobs:
  activation:
    name: Request Manual Activation File 🚀
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Request manual activation file
        uses: game-ci/unity-runner@v4
        id: getManualActivationFile
        with:
          entrypoint: /request_activation.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: manual-activation-file
          path: ${{ steps.getManualActivationFile.outputs.filePath }}
